### PR TITLE
fix: auto switch theme behavior & footer theme indicator

### LINKED ISSUE #4659: Autoswitch theme causing the footer theme indicator to show wrong theme

### PR DESCRIPTION
**Pull request by sanidhyas3s**
- Changing manually to a preset or custom theme now turns auto switch theme mode off with a notification. And now the auto switch mode does override the custom theme as well (statement in settings also updated), priority simply given to the last way theme was modified.

- Fixes #4659, that is the footer theme is now correctly displayed with auto switch themes as well.

### CODE REVIEW

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6342827952

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6343959925

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6344000764

**Comment by monkeytypegeorge** [comment]
Continuous integration check(s) failed. Please review the failing check's logs and make the necessary changes. https://github.com/monkeytypegame/monkeytype/actions/runs/6344247626

File: frontend/src/ts/config.ts [hunk 1]
```diff
@@ -1327,6 +1327,15 @@ export function setAutoSwitchTheme(
...
 
+export function setAutoSwitchThemeOff(): void {
+  if (!config.autoSwitchTheme) return;
+  config.autoSwitchTheme = false;
+  saveToLocalStorage("autoSwitchTheme", undefined);
+  ConfigEvent.dispatch("autoSwitchTheme", config.autoSwitchTheme);
+  Notifications.add("Auto switch theme disabled", 0);
+  return;
+}
+
```
Comment (Miodec) [inline frontend/src/ts/config.ts:1338]: Why add this? Why not just call `setAutoSwitchTheme(false)`?

File: frontend/src/ts/controllers/theme-controller.ts [hunk 2]
```diff
@@ -177,8 +181,8 @@ const debouncedPreview = debounce(
   }
 );
 
-function set(themeIdentifier: string): void {
-  apply(themeIdentifier);
+function set(themeIdentifier: string, isAutoSwitch = false): void {
+  apply(themeIdentifier, undefined, true, isAutoSwitch);
```
Comment (Miodec) [inline frontend/src/ts/controllers/theme-controller.ts:185]: Do we really need to pass it through to `apply`?

Comment (sanidhyas3s) [reply frontend/src/ts/controllers/theme-controller.ts:185]: No, we don't. Fixing it quickly to be handled within `set` itself!

File: frontend/src/ts/config.ts (hunk 1 above)
Comment (Miodec) [reply frontend/src/ts/config.ts]: It was looping because you are setting autoswitchtheme to off when reacting to autoswitchtheme being changed to off. I added a check where its only set to off if its already on, and its all good.

**Comment by sanidhyas3s** [comment]
@Miodec You removed the notification as well with the function, shall I add that in a new PR?

**Comment by Miodec** [comment]
> @Miodec You removed the notification as well with the function, shall I add that in a new PR?

Yeah, sure
