### PR TITLE
fix: crt funbox causes webkit browsers to go into refresh loop (fehmer)

### LINKED ISSUE #4553: CRT funbox causes webkit browsers to go into a refresh loop

### PR DESCRIPTION
**Pull request by fehmer**
Closes #4553 

- detect safari version 16.5 or earlier and don't activate CRT funbox
- converted nested css into plain in  `crt.css`

### CODE REVIEW

**Comment by Miodec** [comment]
If its a WIP please open as draft

File: frontend/src/ts/test/funbox/funbox.ts [hunk 1]
```diff
@@ -700,6 +700,22 @@ FunboxList.setFunboxFunctions("morse", {
 
 FunboxList.setFunboxFunctions("crt", {
   applyGlobalCSS(): void {
+    const isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
+    if (isSafari) {
+      //Workaround for bug https://bugs.webkit.org/show_bug.cgi?id=256171 in Safari 16.5 or earlier
+      const versionMatch = navigator.userAgent.match(
+        /.*Version\/([0-9]*)\.([0-9]*).*/
+      );
+      const mainVersion = versionMatch != null ? parseInt(versionMatch[1]) : 0;
```
Comment (Ferotiq) [inline frontend/src/ts/test/funbox/funbox.ts:709]: Please use strict equalities and inequalities (!==)

Comment (fehmer) [reply frontend/src/ts/test/funbox/funbox.ts]: 👍
