### PR TITLE
fix(theme): random theme switcher (mitjans)

### LINKED ISSUE #5531: Issues with random theme
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

cmitjans

### Account config

{"theme":"9009","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["vscode","metaverse","9009","rgb","red_dragon","shadow","menthol","dark_note","fire","alpine","terror_below"],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"tab","punctuation":false,"numbers":false,"words":50,"time":15,"mode":"time","quoteLength":[1],"language":"english","fontSize":2,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"underline","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"bar","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":true,"randomTheme":"on","timerColor":"main","timerOpacity":"0.25","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"dynamic","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"on","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":0,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"next_word","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"on","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":0}

### Current Behavior

I have detected 2 issues when using the feature "Random theme"
1. The default theme is applied when opening the command line. I would expect the random theme to be kept when the command line opens. I would want to (for example) add the current random theme to my favorites if I like it.
2. When fixing the previous issue, I found out that the feature "Add current theme to favorite"/"Remove current theme from favorite" only works with the currently selected theme, and not the currently applied theme.

### Expected Behavior

1. The random theme should be kept when opening the command line
2. The current applied theme should be considered when adding/removing "current theme" to favorites

### Steps To Reproduce

1. Activate "Random theme > On" from the command line
2. Activate "Next random theme" from the command line
3. Open the command line again, the user's default theme is applied

### Environment

- OS: Mac OS
- Browser: Brave (Chromium)
- Browser Version: 1.67.119

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mitjans**
### Description

There are 2 main changes in this PR:
1. When adding/removing "current theme" to/from favorites it now checks if we are using a random theme as well
	- Relevant file: `frontend/src/ts/commandline/lists/add-or-remove-theme-to-favorites.ts`
2. Treat random themes as normal themes, and not as "previews". This way, when the command line is open, the user's selected theme is not applied, removing any random theme while doing so.

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language or a theme?
  - [ ] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
  - [ ] If is a theme, did you add the theme.css?
    - Also please add a screenshot of the theme, it would be extra awesome if you do so!
- [ ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [ ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username inside parentheses at the end of the PR title

Closes #5531

### CODE REVIEW

File: frontend/src/ts/commandline/lists/themes.ts [hunk 1]
```diff
@@ -37,7 +37,8 @@ function update(themes: MonkeyTypes.Theme[]): void {
           // previewTheme(theme.name);
           ThemeController.preview(theme.name);
         },
-        exec: (): void => {
+        exec: async (): Promise<void> => {
+          await ThemeController.clearRandom();
```
Comment (Miodec) [inline frontend/src/ts/commandline/lists/themes.ts:41]: Instead of exporting clearRandom, why not call it inside setTheme?

Comment (mitjans) [reply frontend/src/ts/commandline/lists/themes.ts:41]: You are right, we don't need to call `clearRandom`, here or inside `setTheme`.

`setTheme` will emit the event `"theme"`, and in `theme-controller.ts` is the first thing we do when this event is received.

```
  if (eventKey === "theme") {
    await clearRandom();
    await clearPreview(false);
    await set(eventValue as string);
  }
  ```

**Review by Miodec — APPROVED** [review]
Thanks
