### PR TITLE
fix(inbox): size indicator not updating on item deletion (@byseif21)

### LINKED ISSUE #6648: Inbox size does not reset after deleting items
### Did you clear cache before opening an issue?

- [x] I have cleared my cache

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

SamLonneman

### Account config

{"theme":"8008","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"smoothCaret":"medium","codeUnindentOnBackspace":false,"quickRestart":"off","punctuation":false,"numbers":false,"words":10,"time":15,"mode":"time","quoteLength":[2],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":[],"confidenceMode":"off","indicateTypos":"off","timerStyle":"off","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","keymapSize":1,"fontFamily":"JetBrains_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":0.5,"startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"https://preview.redd.it/1920x1080-topography-wallpapers-made-by-me-request-for-v0-j8m6ykh6ar1a1.jpg?width=1080&crop=smart&auto=webp&s=7eb82c2a583124b0681924c28b9b78acde098bbd","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1],"customLayoutfluid":["qwerty","dvorak","colemak"],"customPolyglot":["english","spanish","french","german"],"monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off","tapeMargin":50,"maxLineWidth":0}

### Current Behavior

When I delete items from my inbox, the inbox size indicator does not reset or disappear. For example, when I have one item in my inbox, there is an indicator saying "1/25". When I delete the item, the indicator still says "1/25" and remains this way until refreshing.

### Expected Behavior

When I delete an item from my inbox, the inbox size indicator should decrement accordingly. When I delete all items from my inbox, the indicator should disappear entirely (to match the appearance of an empty inbox after refreshing).

### Steps To Reproduce

1. Click the bell icon in the upper right corner.
2. Find the section "Inbox"
4. Assuming you have inbox items, Click "Claim all"
5. Click "Delete all"
6. Notice that the inbox size indicator does not change accordingly until you refresh.

This bug can also be reproduced by deleting inbox items one by one.

### Environment

- OS: Windows 11 Pro (Version 24H2)
- Browser: Google Chrome
- Browser Version: 137.0.7151.104 (Official Build) (64-bit)

## Screen recording of bug when using "Delete all":
https://github.com/user-attachments/assets/e3926949-94f0-4821-a484-2e890e463ed8

## Screen recording of bug when deleting inbox item individually:
https://github.com/user-attachments/assets/f3f18bab-c89d-4dda-9bc0-9e2d29d8ffae

### PR DESCRIPTION
**Pull request by byseif21**
### Description

Closes #6648

### CODE REVIEW

File: frontend/src/ts/elements/alerts.ts [hunk 1]
```diff
@@ -301,9 +301,26 @@ export function setNotificationBubbleVisible(tf: boolean): void {
...
+  const unreadCount = accountAlerts.filter(
+    (alert) =>
+      !alert.read &&
+      !mailToMarkRead.includes(alert.id) &&
+      !mailToDelete.includes(alert.id)
+  ).length;
+
+  DB.updateInboxUnreadSize(unreadCount);
+  setNotificationBubbleVisible(unreadCount > 0);
 }
```
Comment (Miodec) [inline frontend/src/ts/elements/alerts.ts]: Not sure if this is needed. The bubble will always be hidden when the panel is closed. I would move the snapshot update function to the `hide` function.

File: frontend/src/ts/elements/alerts.ts [hunk 2]
```diff
@@ -301,9 +301,26 @@ export function setNotificationBubbleVisible(tf: boolean): void {
...
-  $("#alertsPopup .accountAlerts .title .right").text(
-    `${accountAlerts.length}/${maxMail}`
-  );
+  const remainingItems = accountAlerts.length - mailToDelete.length;
+  if (remainingItems > 0) {
+    $("#alertsPopup .accountAlerts .title .right").text(
+      `${remainingItems}/${maxMail}`
+    );
+  } else {
+    $("#alertsPopup .accountAlerts .title .right").text("");
```
Comment (Miodec) [inline frontend/src/ts/elements/alerts.ts]:
```
.text(`0/${maxMail}`)
```

**Review by Miodec — CHANGES_REQUESTED** [review]

File: frontend/src/ts/elements/alerts.ts (hunk 1 above)
Comment (byseif21) [reply frontend/src/ts/elements/alerts.ts]: yah right

File: frontend/src/ts/elements/alerts.ts [hunk 3]
```diff
@@ -301,9 +302,14 @@ export function setNotificationBubbleVisible(tf: boolean): void {
...
-    `${accountAlerts.length}/${maxMail}`
-  );
+  const remainingItems = accountAlerts.length - mailToDelete.length;
+  if (remainingItems > 0) {
+    $("#alertsPopup .accountAlerts .title .right").text(
+      `${remainingItems}/${maxMail}`
+    );
+  } else {
+    $("#alertsPopup .accountAlerts .title .right").text(`0/${maxMail}`);
+  }
```
Comment (Miodec) [inline frontend/src/ts/elements/alerts.ts]: This could be simplified to just
```ts
const remainingItems = accountAlerts.length - mailToDelete.length;
$("#alertsPopup .accountAlerts .title .right").text(`${remainingItems}/${maxMail}`);
```

right?

**Review by Miodec — CHANGES_REQUESTED** [review]
Thanks

File: frontend/src/ts/elements/alerts.ts (hunk 3 above)
Comment (byseif21) [reply frontend/src/ts/elements/alerts.ts]: sure!
